---
# This tasklist will ensure that the docker runtime is installed properly on the target machine
# The machine is expected to be running ubuntu

# Prerequisite packages
- name: ensure linux-image-extra(uname) installed
  apt: name=linux-image-extra-{{ ansible_kernel }} update_cache=yes

- name: ensure linux-image-extra-virtual installed
  apt: name=linux-image-extra-virtual

- name: ensure ca-certificates installed
  apt: name=ca-certificates

- name: ensure apt-transport-https installed
  apt: name=apt-transport-https

# Set up Docker PPA in APT.
#
# Proxy or firewall problems? Workaround: use "force=yes" on things from docker PPA
- name: ensure gpg key for docker APT repo
  become: true
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: ensure docker-sources.list with docker PPA for apt-get
  template: src=docker-sources.list.j2 dest=/etc/apt/sources.list.d/docker-sources.list owner=root group=root mode=0644

- name: ensure docker-engine installed
  apt: name=docker-engine state=present update_cache=yes force=yes

- name: ensure docker daemon started
  service: name=docker state=started

- name: ensure pip is installed
  apt: name=python-pip state=latest

- name: ensure docker support for Ansible
  pip: name=docker-py state=latest
